services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_container
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa$$word!"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
